//! CDP (Chrome DevTools Protocol) Script Execution
//!
//! This module provides runtime interpretation of CDP scripts generated by Claude.
//! Scripts are stored as JSON files and executed dynamically without compilation.

pub mod claude_prompt;
pub mod executor;
pub mod generator;
pub mod script;
pub mod validation;

pub use claude_prompt::{generate_cdp_script_prompt, validate_generated_script};
pub use executor::CdpExecutor;
pub use generator::CdpScriptGenerator;
pub use script::{CdpCommand, CdpScript, CommandResult, CommandStatus, ExecutionReport};
pub use validation::{
    CdpValidator, ErrorLocation, ParamType, ValidationError, ValidationErrorType, ValidationResult,
};
